return {
    descriptions={
        Back={
            b_abandoned={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_anaglyph={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_black={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_blue={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_challenge={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_checkered={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_erratic={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_ghost={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_green={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_magic={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_nebula={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_painted={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_plasma={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_red={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_yellow={
                name="Aga",
                text={
                    "Aga",
                },
            },
            b_zodiac={
                name="Aga",
                text={
                    "Aga",
                },
            },
        },
        Blind={
            bl_arm={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_big={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_club={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_eye={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_final_acorn={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_final_bell={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_final_heart={
               name="Aga",
                text={
                    "Aga",
                },
            },
            bl_final_leaf={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_final_vessel={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_fish={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_flint={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_goad={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_head={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_hook={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_house={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_manacle={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_mark={
               name="Aga",
                text={
                    "Aga",
                },
            },
            bl_mouth={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_needle={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_ox={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_pillar={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_plant={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_psychic={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_serpent={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_small={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_tooth={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_wall={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_water={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_wheel={
                name="Aga",
                text={
                    "Aga",
                },
            },
            bl_window={
                name="Aga",
                text={
                    "Aga",
                },
            },
        },
        Edition={
            e_base={
               name="Aga",
                text={
                    "Aga",
                },
            },
            e_foil={
                name="Aga",
                text={
                    "Aga",
                },
            },
            e_holo={
                name="Aga",
                text={
                    "Aga",
                },
            },
            e_nagative={
                name="Aga",
                text={
                    "Aga",
                },
            },
            e_nagative_consumable={
               name="Aga",
                text={
                    "Aga",
                },
            },
            e_polychrome={
                name="Aga",
                text={
                    "Aga",
                },
            },
        },
        Enhanced={
            m_bonus={
                name="Aga",
                text={
                    "Aga",
                },
            },
            m_glass={
               name="Aga",
                text={
                    "Aga",
                },
            },
            m_gold={
                name="Aga",
                text={
                    "Aga",
                },
            },
            m_lucky={
                name="Aga",
                text={
                    "Aga",
                },
            },
            m_mult={
                name="Aga",
                text={
                    "Aga",
                },
            },
            m_steel={
                name="Aga",
                text={
                    "Aga",
                },
            },
            m_stone={
                name="Aga",
                text={
                    "Aga",
                },
            },
            m_wild={
                name="Aga",
                text={
                    "Aga",
                },
            },
        },
        Joker={
            j_8_ball={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_abstract={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_acrobat={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                    "{C:inactive}(#2#)",
                },
            },
            j_ancient={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_arrowhead={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_astronomer={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_banner={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_baron={
               name="Aga",
                text={
                    "Aga",
                },
            },
            j_baseball={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_blackboard={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_bloodstone={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_blue_joker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_blueprint={
                nname="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_bootstraps={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_brainstorm={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_bull={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_burglar={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_burnt={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_business={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_caino={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_campfire={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_card_sharp={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_cartomancer={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_castle={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_cavendish={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_ceremonial={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_certificate={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_chaos={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_chicot={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_clever={
               name="Aga",
                text={
                    "Aga",
                },
            },
            j_cloud_9={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_constellation={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_crafty={
               name="Aga",
                text={
                    "Aga",
                },
            },
            j_crazy={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_credit_card={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_delayed_grat={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_devious={
               name="Aga",
                text={
                    "Aga",
                },
            },
            j_diet_cola={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_dna={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_drivers_license={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_droll={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_drunkard={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_duo={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_dusk={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_egg={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_erosion={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_even_steven={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_faceless={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_family={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_fibonacci={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_flash={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_flower_pot={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_fortune_teller={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_four_fingers={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_gift={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_glass={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_gluttenous_joker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_golden={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_greedy_joker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_green_joker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_gros_michel={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_hack={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_half={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_hallucination={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_hanging_chad={
               name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_hiker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_hit_the_road={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_hologram={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_ice_cream={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_idol={
               name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_invisible={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_joker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_jolly={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_juggler={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_loyalty_card={
               name="Aga",
                text={
                    "Aga",
                },
            },
            j_luchador={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_lucky_cat={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_lusty_joker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_mad={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_madness={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_mail={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_marble={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_matador={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_merry_andy={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_midas_mask={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_mime={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_misprint={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_mr_bones={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_mystic_summit={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_obelisk={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_odd_todd={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_onyx_agate={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_oops={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_order={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_pareidolia={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_perkeo={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_photograph={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_popcorn={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_raised_fist={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_ramen={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_red_card={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_reserved_parking={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_ride_the_bus={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_riff_raff={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_ring_master={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_rocket={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_rough_gem={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_runner={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_satellite={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_scary_face={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_scholar={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_seance={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_seeing_double={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_selzer={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_shoot_the_moon={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_shortcut={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_sixth_sense={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_sly={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_smeared={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_smiley={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_sock_and_buskin={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_space={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_splash={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_square={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_steel_joker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_stencil={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_stone={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_stuntman={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_supernova={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_superposition={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_swashbuckler={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_throwback={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_ticket={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_to_the_moon={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_todo_list={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_trading={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_tribe={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_triboulet={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_trio={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_troubadour={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_trousers={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_turtle_bean={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_vagabond={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_vampire={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_walkie_talkie={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_wee={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_wily={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_wrathful_joker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            j_yorick={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            j_zany={
                name="Aga",
                text={
                    "Aga",
                },
            },
        },
        Other={
            black_sticker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            blue_seal={
                name="Aga",
                text={
                    "Aga",
                },
            },
            blue_sticker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            card_chips={
                text={
                    "Aga",
                },
            },
            card_extra_chips={
                text={
                    "Aga",
                },
            },
            challenge_locked={
                name="Aga",
                text={
                    "Aga",
                },
            },
            debuffed_default={
                name="Aga",
                text={
                    "Aga",
                },
            },
            debuffed_playing_card={
                name="Aga",
                text={
                    "Aga",
                },
            },
            deck_locked_discover={
                name="Aga",
                text={
                    "Aga",
                },
            },
            deck_locked_stake={
                name="Aga",
                text={
                    "Aga",
                },
            },
            deck_locked_win={
                name="Aga",
                text={
                    "Aga",
                },
            },
            demo_locked={
                name="Aga",
                text={
                    "Aga",
                },
            },
            demo_shop_locked={
                name="Aga",
                text={
                    "Aga",
                },
            },
            eternal={
                name="Aga",
                text={
                    "Aga",
                },
            },
            gold_seal={
                name="Aga",
                text={
                    "Aga",
                },
            },
            gold_sticker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            green_sticker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            joker_locked_legendary={
                name="Aga",
                text={
                    "Aga",
                },
            },
            locked={
                name="Aga",
                text={
                    "Aga",
                },
            },
            orange_sticker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_arcana_jumbo={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_arcana_mega={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_arcana_normal={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_buffoon_jumbo={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_buffoon_mega={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_buffoon_normal={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_celestial_jumbo={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_celestial_mega={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_celestial_normal={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_spectral_jumbo={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_spectral_mega={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_spectral_normal={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_standard_jumbo={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_standard_mega={
                name="Aga",
                text={
                    "Aga",
                },
            },
            p_standard_normal={
                name="Aga",
                text={
                    "Aga",
                },
            },
            perishable={
                name="Aga",
                text={
                    "Aga",
                },
            },
            pinned_left={
                name="Aga",
                text={
                    "Aga",
                },
            },
            playing_card={
                text={
                    "Aga",
                },
            },
            purple_seal={
                name="Aga",
                text={
                    "Aga",
                },
            },
            purple_sticker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            red_seal={
                name="Aga",
                text={
                    "Aga",
                },
            },
            red_sticker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            remove_nagative={
                name="Aga",
                text={
                    "Aga",
                },
            },
            rental={
                name="Aga",
                text={
                    "Aga",
                },
            },
            undiscovered_booster={
                name="Aga",
                text={
                    "Aga",
                },
            },
            undiscovered_edition={
                name="Aga",
                text={
                    "Aga",
                },
            },
            undiscovered_joker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            undiscovered_planet={
                name="Aga",
                text={
                    "Aga",
                },
            },
            undiscovered_spectral={
                name="Aga",
                text={
                    "Aga",
                },
            },
            undiscovered_tag={
                name="Aga",
                text={
                    "Aga",
                },
            },
            undiscovered_tarot={
                name="Aga",
                text={
                    "Aga",
                },
            },
            undiscovered_voucher={
                name="Aga",
                text={
                    "Aga",
                },
            },
            white_sticker={
                name="Aga",
                text={
                    "Aga",
                },
            },
            wip_locked={
                name="Aga",
                text={
                    "Aga",
                },
            },
        },
        Planet={
            c_ceres={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_earth={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_eris={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_jupiter={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_mars={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_mercury={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_neptune={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_planet_x={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_pluto={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_saturn={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_uranus={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_venus={
                name="Aga",
                text={
                    "Aga",
                },
            },
        },
        Spectral={
            c_ankh={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_aura={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_black_hole={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_cryptid={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_deja_vu={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_ectoplasm={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_familiar={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_grim={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_hex={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_immolate={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_incantation={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_medium={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_ouija={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_sigil={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_soul={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_talisman={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_trance={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_wraith={
                name="Aga",
                text={
                    "Aga",
                },
            },
        },
        Stake={
            stake_black={
                name="Aga",
                text={
                    "Aga",
                },
            },
            stake_blue={
                name="Aga",
                text={
                    "Aga",
                },
            },
            stake_gold={
                name="Aga",
                text={
                    "Aga",
                },
            },
            stake_green={
                name="Aga",
                text={
                    "Aga",
                },
            },
            stake_orange={
                name="Aga",
                text={
                    "Aga",
                },
            },
            stake_purple={
                name="Aga",
                text={
                    "Aga",
                },
            },
            stake_red={
                name="Aga",
                text={
                    "Aga",
                },
            },
            stake_white={
                name="Aga",
                text={
                    "Aga",
                },
            },
        },
        Tag={
            tag_boss={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_buffoon={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_charm={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_coupon={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_d_six={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_double={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_economy={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_ethereal={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_foil={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_garbage={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_handy={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_holo={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_investment={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_juggle={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_meteor={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_nagative={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_orbital={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_polychrome={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_rare={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_skip={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_standard={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_top_up={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_uncommon={
                name="Aga",
                text={
                    "Aga",
                },
            },
            tag_voucher={
                name="Aga",
                text={
                    "Aga",
                },
            },
        },
        Tarot={
            c_chariot={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_death={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_devil={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_emperor={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_empress={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_fool={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_hanged_man={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_heirophant={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_hermit={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_high_priestess={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_judgement={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_justice={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_lovers={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_magician={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_moon={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_star={
               name="Aga",
                text={
                    "Aga",
                },
            },
            c_strength={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_sun={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_temperance={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_tower={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_wheel_of_fortune={
                name="Aga",
                text={
                    "Aga",
                },
            },
            c_world={
                name="Aga",
                text={
                    "Aga",
                },
            },
        },
        Voucher={
            v_antimatter={
            name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_blank={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_clearance_sale={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_crystal_ball={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_directors_cut={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_glow_up={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_grabber={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_hieroglyph={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_hone={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_illusion={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_liquidation={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_magic_trick={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_money_tree={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_nacho_tong={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_observatory={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_omen_globe={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_overstock_norm={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_overstock_plus={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_paint_brush={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_palette={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_petroglyph={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_planet_merchant={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_planet_tycoon={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_recyclomancy={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_reroll_glut={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_reroll_surplus={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_retcon={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_seed_money={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_tarot_merchant={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_tarot_tycoon={
                name="Aga",
                text={
                    "Aga",
                },
                unlock={
                    "Aga",
                },
            },
            v_telescope={
                name="Aga",
                text={
                    "Aga",
                },
            },
            v_wasteful={
                name="Aga",
                text={
                    "Aga",
                },
            },
        },
    },
    misc={
        achievement_descriptions={
            _100000k="Aga",
            _1000k="Aga",
            _10k="Aga",
            ante_up="Aga",
            ante_upper="Aga",
            astronomy="Aga",
            big_hands="Aga",
            card_discarder="Aga",
            card_player="Aga",
            cartomancy="Aga",
            clairvoyance="Aga",
            completionist="Aga",
            completionist_plus="Aga",
            completionist_plus_plus="Aga",
            extreme_couponer="Aga",
            flushed="Aga",
            heads_up="Aga",
            high_stakes="Aga",
            legendary="Aga",
            low_stakes="Aga",
            mid_stakes="Aga",
            nest_egg="Aga",
            retrograde="Aga",
            roi="Aga",
            royale="Aga",
            rule_bender="Aga",
            rule_breaker="Aga",
            shattered="Aga",
            speedrunner="Aga",
            tiny_hands="Aga",
            you_get_what_you_get="Aga",
        },
        achievement_names={
            _100000k="Aga",
            _1000k="Aga",
            _10k="Aga",
            ante_up="Aga",
            ante_upper="Aga",
            astronomy="Aga",
            big_hands="Aga",
            card_discarder="Aga",
            card_player="Aga",
            cartomancy="Aga",
            clairvoyance="Aga",
            completionist="Aga",
            completionist_plus="Aga",
            completionist_plus_plus="Aga",
            extreme_couponer="Aga",
            flushed="Aga",
            heads_up="Aga",
            high_stakes="Aga",
            legendary="Aga",
            low_stakes="Aga",
            mid_stakes="Aga",
            nest_egg="Aga",
            retrograde="Aga",
            roi="Aga",
            royale="Aga",
            rule_bender="Aga",
            rule_breaker="Aga",
            shattered="Aga",
            speedrunner="Aga",
            tiny_hands="Aga",
            you_get_what_you_get="Aga",
        },
        blind_states={
            Current="Aga",
            Defeated="Aga",
            Select="Aga",
            Selected="Aga",
            Skipped="Aga",
            Upcoming="Aga",
        },
        challenge_names={
            c_blast_off_1="Aga",
            c_bram_poker_1="Aga",
            c_city_1="Aga",
            c_cruelty_1="Aga",
            c_double_nothing_1="Aga",
            c_five_card_1="Aga",
            c_fragile_1="Aga",
            c_golden_needle_1="Aga",
            c_inflation_1="Aga",
            c_jokerless_1="Aga",
            c_knife_1="Aga",
            c_luxury_1="Aga",
            c_mad_world_1="Aga",
            c_medusa_1="Aga",
            c_monolith_1="Aga",
            c_non_perishable_1="Aga",
            c_omelette_1="Aga",
            c_rich_1="Aga",
            c_typecast_1="Aga",
            c_xray_1="Aga",
        },
        collabs={
            Clubs={
                ["1"]="Aga",
                ["2"]="Aga",
                ["3"]="Aga",
                ["4"]="Aga",
                ["5"]="Aga",
                ["6"]="Aga",
                ["7"]="Aga",
            },
            Diamonds={
                ["1"]="Aga",
                ["2"]="Aga",
                ["3"]="Aga",
                ["4"]="Aga",
                ["5"]="Aga",
                ["6"]="Aga",
                ["7"]="Aga",
            },
            Hearts={
                ["1"]="Aga",
                ["2"]="Aga",
                ["3"]="Aga",
                ["4"]="Aga",
                ["5"]="Aga",
                ["6"]="Aga",
                ["7"]="Aga",
            },
            Spades={
                ["1"]="Aga",
                ["2"]="Aga",
                ["3"]="Aga",
                ["4"]="Aga",
                ["5"]="Aga",
                ["6"]="Aga",
                ["7"]="Aga",
            },
        },
        dictionary={
            ["$"]="$",
            b_FAQ="Aga",
            b_and_use="Aga",
            b_back="Aga",
            b_blinds="Aga",
            b_booster_packs="Aga",
            b_buy="Aga",
            b_cash_out="Aga",
            b_challenges="Aga",
            b_collection="Aga",
            b_collection_cap="Aga",
            b_continue="Aga",
            b_copy="Aga",
            b_copy_seed="Aga",
            b_create_profile="Aga",
            b_credits="Aga",
            b_current_profile="Aga",
            b_customize_deck="Aga",
            b_deck="Aga",
            b_decks="Aga",
            b_delete_profile="Aga",
            b_discard="Aga",
            b_editions="Aga",
            b_endless="Aga",
            b_enhanced_cards="Aga",
            b_full_deck="Aga",
            b_high_contrast_cards="Aga",
            b_how_to_play="Aga",
            b_imagery="Aga",
            b_jokers="Aga",
            b_load_profile="Aga",
            b_main_menu="Aga",
            b_music="Aga",
            b_new_challenge="Aga",
            b_new_run="Aga",
            b_next="Aga",
            b_next_round_1="Aga",
            b_next_round_2="Aga",
            b_open="Aga",
            b_options="Aga",
            b_options_cap="Aga",
            b_planet_cards="Aga",
            b_play_cap="Aga",
            b_play_hand="Aga",
            b_playbalatro="Aga",
            b_poker_hands="Aga",
            b_quit_cap="Aga",
            b_redeem="Aga",
            b_reduced_motion="Aga",
            b_remaining="Aga",
            b_reroll_boss="Aga",
            b_reset_profile="Aga",
            b_restrictions="Aga",
            b_retry="Aga",
            b_rules="Aga",
            b_run_info_1="Aga",
            b_run_info_2="Aga",
            b_seals="Aga",
            b_seed="Aga",
            b_select="Aga",
            b_sell="Aga",
            b_set_CRT="Aga",
            b_set_CRT_bloom="Aga",
            b_set_apply="Aga",
            b_set_audio="Aga",
            b_set_crash_reports="Aga",
            b_set_game="Aga",
            b_set_game_vol="Aga",
            b_set_gamespeed="Aga",
            b_set_graphics="Aga",
            b_set_master_vol="Aga",
            b_set_monitor="Aga",
            b_set_music_vol="Aga",
            b_set_pixel_smoothing="Aga",
            b_set_play_discard_pos="Aga",
            b_set_rumble="Aga",
            b_set_screenshake="Aga",
            b_set_shadows="Aga",
            b_set_vibration="Aga",
            b_set_video="Aga",
            b_set_windowmode="Aga",
            b_settings="Aga",
            b_skip="Aga",
            b_skip_blind="Aga",
            b_skip_reward="Aga",
            b_sort_hand="Aga",
            b_sounds="Aga",
            b_spectral_cards="Aga",
            b_stake="Aga",
            b_start_new_run="Aga",
            b_stat_consumables="Aga",
            b_stat_jokers="Aga",
            b_stat_planets="Aga",
            b_stat_spectrals="Aga",
            b_stat_tarots="Aga",
            b_stat_vouchers="Aga",
            b_stats="Aga",
            b_tags="Aga",
            b_tarot_cards="Aga",
            b_unlock_all="Aga",
            b_use="Aga",
            b_vouchers="Aga",
            b_wishlist="Aga",
            k_aces="Aga",
            k_achievement="Aga",
            k_achievements_disabled="Aga",
            k_active="Aga",
            k_active_ex="Aga",
            k_again_ex="Aga",
            k_all_hands="Aga",
            k_also_applied="Aga",
            k_ante="Aga",
            k_ante_cap="Aga",
            k_arcana_pack="Aga",
            k_balanced="Aga",
            k_banned_cards="Aga",
            k_banned_tags="Aga",
            k_base_cap="Aga",
            k_base_cards="Aga",
            k_best_hand="Aga",
            k_booster="Aga",
            k_buffoon_pack="Aga",
            k_cap_consumables="Aga",
            k_card_stats="Aga",
            k_celestial_pack="Aga",
            k_challenge_mode="Aga",
            k_challenges="Aga",
            k_choose="Aga",
            k_collection="Aga",
            k_common="Aga",
            k_compatible="Aga",
            k_copied_ex="Aga",
            k_custom_rules="Aga",
            k_daily_run="Aga",
            k_debuffed="Aga",
            k_deck="Aga",
            k_deck_stake_wins="Aga",
            k_defeated_by="Aga",
            k_demo_version_ex="Aga",
            k_disabled_ex="Aga",
            k_drank_ex="Aga",
            k_duplicated_ex="Aga",
            k_dwarf_planet="Aga",
            k_eaten_ex="Aga",
            k_edition="Aga",
            k_effective="Aga",
            k_empty_caps="Aga",
            k_enter_name="Aga",
            k_enter_seed="Aga",
            k_enter_text="Aga",
            k_eroded_ex="Aga",
            k_extinct_ex="Aga",
            k_face_cards="Aga",
            k_game_modifiers="Aga",
            k_gold="Aga",
            k_high_score_ex="Aga",
            k_hud_discards="Aga",
            k_hud_hands="Aga",
            k_incompatible="Aga",
            k_joker="Aga",
            k_joker_stickers="Aga",
            k_jokers_cap="Aga",
            k_legendary="Aga",
            k_level_prefix="Aga",
            k_level_up_ex="Aga",
            k_locked="Aga",
            k_lower_score="Aga",
            k_lvl="Aga",
            k_melted_ex="Aga",
            k_money="Aga",
            k_mult="Aga",
            k_no_other_jokers="Aga",
            k_no_reward="Aga",
            k_no_room_ex="Aga",
            k_no_space_ex="Aga",
            k_none="Aga",
            k_nope_ex="Aga",
            k_not_allowed_ex="Aga",
            k_not_discovered="Aga",
            k_numbered_cards="Aga",
            k_or="Aga",
            k_other="Aga",
            k_page="Aga",
            k_planet="Aga",
            k_planet_q="Aga",
            k_playing_as="Aga",
            k_plus_joker="Aga",
            k_plus_planet="Aga",
            k_plus_spectral="Aga",
            k_plus_stone="Aga",
            k_plus_tarot="Aga",
            k_poker_hand="Aga",
            k_profile="Aga",
            k_progress="Aga",
            k_rank="Aga",
            k_rare="Aga",
            k_redeemed_ex="Aga",
            k_reroll="Aga",
            k_reset="Aga",
            k_reward="Aga",
            k_round="Aga",
            k_safe_ex="Aga",
            k_saved_ex="Aga",
            k_seed="Aga",
            k_seeded_run="Aga",
            k_skipped_cap="Aga",
            k_spectral="Aga",
            k_spectral_pack="Aga",
            k_stake="Aga",
            k_stake_level="Aga",
            k_standard_pack="Aga",
            k_suit="Aga",
            k_swapped_ex="Aga",
            k_tarot="Aga",
            k_trophies_disabled="Aga",
            k_trophy="Aga",
            k_uncommon="Aga",
            k_undisovered="Aga",
            k_unknown="Aga",
            k_unlocked_ex="Aga",
            k_upgrade_ex="Aga",
            k_val_up="Aga",
            k_view="Aga",
            k_voucher="Aga",
            k_vouchers_cap="Aga",
            k_wins="Aga",
            k_x_base="Aga",
            ml_bloom_opt={
                "Aga",
                "Aga",
            },
            ml_buy_and_use_target={
                "Aga",
                "Aga"
            },
            ml_buy_target={
                "Aga",
            },
            ml_card_stats={
                "Aga",
                "Aga",
            },
            ml_controller_required={
                "Aga",
                "Aga",
            },
            ml_crash_report_info={
                "Aga",
                "Aga",
                "Aga",
            },
            ml_demo_thanks_message={
                "Aga",
                "Aga",
                "Aga",
            },
            ml_disabled_seed={
                "Aga",
                "Aga",
            },
            ml_edition_seal_enhancement_explanation={
                "Aga",
                "Aga",
            },
            ml_eternal={
                "Aga",
                "Aga",
                "Aga",
            },
            ml_gold_seal_desc={
                "Aga",
                "Aga",
                "Aga",
            },
            ml_offline_message={
                "Aga",
                "Aga",
            },
            ml_open_target={
                "Aga",
            },
            ml_paste_seed={
                "Aga",
                "Aga",
            },
            ml_play_discard_pos_opt={
                "Aga",
                "Aga",
            },
            ml_redeem_target={
                "Aga",
            },
            ml_sell_target={
                "Aga",
            },
            ml_shadow_opt={
                "Aga",
                "Aga",
            },
            ml_smoothing_opt={
                "Aga",
                "Aga",
            },
            ml_unlock_all_explanation={
                "Aga",
                "Aga",
            },
            ml_unlock_all_trophies={
                "Aga",
                "Aga",
            },
            ml_vsync_opt={
                "Aga",
                "Aga",
            },
            ml_windowmode_opt={
                "Aga",
                "Aga",
                "Aga",
            },
            ph_1_level="Aga",
            ph_4_7_of_clubs="Aga",
            ph_alert_debuff_confirm="Aga",
            ph_all_poker_hand="Aga",
            ph_blind_reward="Aga ",
            ph_blind_score_at_least="Aga",
            ph_boss_disabled="Aga",
            ph_choose_blind_1="Aga",
            ph_choose_blind_2="Aga",
            ph_click_confirm="Aga",
            ph_deck_preview_effective="Aga",
            ph_deck_preview_stones="Aga",
            ph_defeat_the_boss="Aga",
            ph_defeat_this_blind_1="Aga",
            ph_defeat_this_blind_2="Aga",
            ph_demo_thanks_1="Aga",
            ph_demo_thanks_2="Aga",
            ph_display_stickers="Aga",
            ph_game_over="Aga",
            ph_improve_run="Aga",
            ph_most_played="Aga",
            ph_mr_bones="Aga",
            ph_no_boss_active="Aga",
            ph_no_vouchers="Aga",
            ph_score_at_least="Aga",
            ph_score_cards_discarded="Aga",
            ph_score_cards_played="Aga",
            ph_score_cards_purchased="Aga",
            ph_score_furthest_ante="Aga",
            ph_score_furthest_round="Aga",
            ph_score_hand="Aga",
            ph_score_new_collection="Aga",
            ph_score_poker_hand="Aga",
            ph_score_times_rerolled="Aga",
            ph_select_challenge="Aga",
            ph_sneak_peek="Aga",
            ph_stat_consumable="Aga",
            ph_stat_joker="Aga",
            ph_stat_voucher="Aga",
            ph_unscored_hand="Aga",
            ph_up_ante_1="Aga",
            ph_up_ante_2="Aga",
            ph_up_ante_3="Aga",
            ph_vouchers_redeemed="Aga",
            ph_you_win="Aga",
            ph_you_win_demo="Aga",
        },
        high_scores={
            boss_streak="Aga",
            collection="Aga",
            current_streak="",
            furthest_ante="Aga",
            furthest_round="Aga",
            hand="Aga",
            most_money="Aga",
            poker_hand="Aga",
            win_streak="Aga",
        },
        labels={
            blue_seal="Aga",
            common="Aga",
            eternal="Aga",
            foil="Aga",
            gold_seal="Aga",
            holographic="Aga",
            legendary="Aga",
            locked="Aga",
            nagative="Aga",
            perishable="Aga",
            pinned_left="Aga",
            planet="Aga",
            pluto_planet="Aga",
            polychrome="Aga",
            purple_seal="Aga",
            rare="Aga",
            red_seal="Aga",
            rental="Aga",
            tarot="Aga",
            uncommon="Aga",
            voucher="Aga",
        },
        poker_hand_descriptions={
            ["Five of a Kind"]={
                "Aga",
            },
            Flush={
                "Aga",
            },
            ["Flush Five"]={
                "Aga",
            },
            ["Flush House"]={
                "Aga",
                "Aga",
            },
            ["Four of a Kind"]={
                "Aga",
                "Aga",
            },
            ["Full House"]={
                "Aga",
            },
            ["High Card"]={
                "Aga,",
                "Aga",
            },
            Pair={
                "Aga",
                "Aga",
            },
            ["Royal Flush"]={
                "Aga",
                "Aga",
            },
            Straight={
                "Aga",
            },
            ["Straight Flush"]={
                "Aga",
                "Aga",
            },
            ["Three of a Kind"]={
                "Aga",
                "Aga",
            },
            ["Two Pair"]={
                "Aga",
                "Aga",
            },
        },
        poker_hands={
            ["Five of a Kind"]="Aga",
            Flush="Aga",
            ["Flush Five"]="Aga",
            ["Flush House"]="Aga",
            ["Four of a Kind"]="Aga",
            ["Full House"]="Aga",
            ["High Card"]="Aga",
            Pair="Aga",
            ["Royal Flush"]="Aga",
            Straight="Aga",
            ["Straight Flush"]="Aga",
            ["Three of a Kind"]="Aga",
            ["Two Pair"]="Aga",
        },
        quips={
            dq_1={
                "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
            lq_1={
                "Aga",
                "Aga",
                "Aga",
            },
            lq_10={
                "Aga",
            },
            lq_2={
                "Aga",
                "Aga",
            },
            lq_3={
                "Aga",
                "Aga",
                "Aga",
            },
            lq_4={
                "Aga",
                "Aga",
                "Aga",
            },
            lq_5={
                "Aga",
                "Aga",
                "Aga",
            },
            lq_6={
                "Aga",
                "Aga",
            },
            lq_7={
                "Aga",
                "Aga",
            },
            lq_8={
                "Aga",
                "Aga",
                "Aga",
            },
            lq_9={
                "Aga",
                "Aga",
                "Aga",
            },
            wq_1={
                "Aga",
            },
            wq_2={
                "Aga",
                "Aga",
            },
            wq_3={
                "Aga",
                "Aga",
            },
            wq_4={
                "Aga",
                "Aga",
                "Aga",
            },
            wq_5={
                "Aga",
                "Aga",
            },
            wq_6={
                "Aga",
                "Aga",
            },
            wq_7={
                "Aga",
                "Aga",
                "Aga",
            },
        },
        ranks={
            ["10"]="Aga",
            ["2"]="Aga",
            ["3"]="Aga",
            ["4"]="Aga",
            ["5"]="Aga",
            ["6"]="Aga",
            ["7"]="Aga",
            ["8"]="Aga",
            ["9"]="Aga",
            Ace="Aga",
            Jack="Aga",
            King="Aga",
            Queen="Aga",
        },
        suits_plural={
            Clubs="Aga",
            Diamonds="Aga",
            Hearts="Aga",
            Spades="Aga",
        },
        suits_singular={
            Clubs="Aga",
            Diamonds="Aga",
            Hearts="Aga",
            Spades="Aga",
        },
        tutorial={
            bb_1={
                "Aga,",
                "Aga.",
            },
            bb_2={
                "Aga",
                "Aga",
                "{Aga.",
            },
            bb_3={
                "Aga",
                "Aga",
                "Aga",
                "Aga.",
            },
            bb_4={
                "Aga",
                "Aga",
                "Aga",
            },
            bb_5={
                "Aga",
                "Aga",
            },
            fh_1={
                "Aga",
                "Aga",
            },
            fh_2={
                "Aga",
                "Aga",
                "Aga",
            },
            fh_3={
                "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
            fh_4={
                "Aga",
                "Aga",
                "Aga",
            },
            fh_4_touch={
                "Aga",
                "Aga",
                "Aga",
            },
            fh_5={
                "Aga",
                "Aga",
                "Aga",
            },
            fh_5_touch={
                "Aga",
                "Aga",
                "Aga",
            },
            fh_6={
                "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
            fh_7={
                "Aga",
                "Aga",
                "Aga",
            },
            fh_8={
                "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
            s_1={
                "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
            s_10={
                "Aga",
                "Aga",
                "Aga",
            },
            s_11={
                "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
            s_12={
                "Aga",
                "Aga",
            },
            s_2={
                "Aga",
                "Aga",
            },
            s_2_touch={
                "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
            s_3={
                "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
            s_4={
                "Aga",
                "Aga",
            },
            s_5={
                "Aga",
                "Aga",
                "Aga",
            },
            s_6={
                "Aga",
                "Aga",
            },
            s_7={
               "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
            s_8={
                "Aga",
                "Aga",
                "Aga",
            },
            s_9={
                "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
            sb_1={
                "Aga",
                "Aga",
                "Aga",
            },
            sb_2={
                "Aga",
                "Aga",
                "Aga",
            },
            sb_3={
                "Aga",
                "Aga",
                "Aga",
            },
            sb_4={
                "Aga",
                "Aga",
            },
            sh_1={
                "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
            sh_2={
                "Aga",
                "Aga",
            },
            sh_3={
                "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
            sh_3_touch={
                "Aga",
                "Aga",
                "Aga",
                "Aga",
            },
        },
        v_dictionary={
            a_chips="Aga",
            a_chips_minus="Aga",
            a_hands="Aga",
            a_handsize="Aga",
            a_handsize_minus="Aga",
            a_mult="Aga",
            a_mult_minus="Aga",
            a_remaining="Aga",
            a_sold_tally="Aga",
            a_xmult="Aga",
            a_xmult_minus="Aga",
            ante_x_voucher="Aga",
            challenges_completed="Aga",
            completed="Aga",
            deck_preview_wheel_plural="Aga",
            deck_preview_wheel_singular="Aga",
            interest="Aga",
            loyalty_active="Aga",
            loyalty_inactive="Aga",
            ml_foil_desc={
                "Aga",
                "Aga",
            },
            ml_holo_desc={
                "Aga",
                "Aga",
            },
            ml_nagative_consumable_desc={
                "Aga",
                "Aga",
            },
            ml_nagative_desc={
                "Aga",
                "Aga",
            },
            ml_polychrome_desc={
                "Aga",
                "Aga",
            },
            remaining_discard_money="Aga",
            remaining_hand_money="Aga",
            unlocked="Aga",
        },
        v_text={
            ch_c_all_eternal={
                "Aga",
            },
            ch_c_chips_dollar_cap={
                "Aga",
            },
            ch_c_daily={
                "Aga",
            },
            ch_c_debuff_played_cards={
                "Aga",
            },
            ch_c_discard_cost={
                "Aga",
            },
            ch_c_flipped_cards={
                "Aga",
            },
            ch_c_inflation={
                "Aga",
            },
            ch_c_minus_hand_size_per_X_dollar={
                "Aga",
            },
            ch_c_no_extra_hand_money={
                "Aga",
            },
            ch_c_no_interest={
                "Aga",
            },
            ch_c_no_reward={
                "Aga",
            },
            ch_c_no_reward_specific={
                "Aga",
            },
            ch_c_no_shop_jokers={
                "Aga",
            },
            ch_c_none={
                "Aga",
            },
            ch_c_set_eternal_ante={
                "Aga",
            },
            ch_c_set_joker_slots_ante={
                "Aga",
            },
            ch_c_set_seed={
                "Aga",
            },
            ch_m_consumable_slots={
                "Aga",
            },
            ch_m_discards={
                "Aga",
            },
            ch_m_dollars={
                "Aga",
            },
            ch_m_hand_size={
                "Aga",
            },
            ch_m_hands={
                "Aga",
            },
            ch_m_joker_slots={
                "Aga",
            },
            ch_m_none={
                "Aga",
            },
        },
    },
}
